### ISSUE TITLE
Prefetch data provider ignores code membership

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/org-opencds-cqf-cds#21]
The PrefetchDataProvider is ignoring code membership when satisfying a retrieve request. It uses the PrefetchProviderHelper.checkCodeMembership function:

https://github.com/DBCG/org-opencds-cqf-cds/blob/master/src/main/java/org/opencds/cqf/cds/providers/PrefetchDataProviderHelper.java#L193

This code needs to be modified to test for code equivalence (based on system and code only).

**Comment by JPercival** [comment]
Resolved by #22
